//try catch
/*try {
    const ants = false;
    ants = true;

} catch(exception) {
    console.log(exception);
}

//try catch in a loop
for (let i = 0; i < 10; i++) {
    try {
        console.lg(i);
    
    } catch(exception) {
        console.log(exception);
    }
}

//try catch finally
try {
    console.lg('hello');
} catch(e) {
    console.log(e);
} finally {
    console.log('world');
}

//throw
try {
    console.lg('hello');
} catch(e) {
    console.log(e);
    throw(e);
} finally {
    console.log('world');
}

function doSomething() {
    console.log('its done');
}

try {
    cnsole.log('hello mike');
    doSomething();
} catch (e) {
    console.log(e);
} finally {
    console.log('really?');
}*/

